### ISSUE TITLE
Clean release

### ISSUE THREAD

**Issue by agila5** [ropensci/osmextract#118]
I think that now all tests and examples use ITS example so I think we delete the IOW example from the releases of the package and, after the review, create a "proper" 0.1.0 release

**Comment by Robinlovelace** [comment]
Or a 0.1.1 release.

**Comment by agila5** [comment]
Hi @Robinlovelace. If you don't have any other comment, I think we are ready for 0.2 release and then CRAN submission.

**Comment by Robinlovelace** [comment]
The soon it's on CRAN the better! Great package, using it for my work today and sure other people will find it useful.
