### ISSUE TITLE
Explore colored terminal output

### ISSUE THREAD

**Issue by agila5** [ropensci/osmextract#133]
The package may return several "terminal output" like notes, messages, warnings and errors (and they may be quite verbose, including a lot of descriptions). I think it could be nice to test a coloured terminal output to easily distinguish between a note, an important message or a warning. 

The only package that I know related to this topic is: https://github.com/r-lib/crayon

See also https://github.com/r-lib/cli#readme

**Comment by agila5** [comment]
Something like this (I cannot use reprex since md output ignores the colors): 

![immagine](https://user-images.githubusercontent.com/22221146/111976635-214fb780-8b02-11eb-94c5-dfce7b101337.png)

**Comment by agila5** [comment]
This is probably unnecessarily complicated...

**Comment by Robinlovelace** [comment]
> This is probably unnecessarily complicated...

:laughing: agree jeje
