### ISSUE TITLE
CRAN policy for internet connection

### ISSUE THREAD

**Issue by agila5** [ropensci/osmextract#147]
See https://cran.r-project.org/web/packages/policies.html

> Packages which use Internet resources should fail gracefully with an informative message if the resource is not available or has changed (and not give a check warning nor error). 

Not sure if this is a real problem (but it might be, see https://github.com/ITSLeeds/osmextract/actions/runs/346224452). Check the examples/tests.

**Comment by agila5** [comment]
The same problem exists for vignettes and examples.

**Comment by agila5** [comment]
> 👍 Important to test it in internet free environments. Simple way: turn the wifi off and run the tests!

That's exactly what happened :sweat_smile: I run RCMD check without turning on the wifi and I got tons of errors.

**Comment by Robinlovelace** [comment]
FYI the pct package breaks the rules pretty badly. I think it's good to aim for best practice though for sure.

**Comment by Robinlovelace** [comment]
I think it passes CRAN policy for now.
