### ISSUE TITLE
Check the output of oe_get_keys

### ISSUE THREAD

**Issue by agila5** [ropensci/osmextract#162]
``` r
library(osmextract)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright.
#> Check the package website for more details.
iow <- oe_get("Isle of Wight")
oe_get_keys(iow)[c(14, 15, 19)]
#> [1] "not:name"          "source:maxspeed"   "parking:lane:both"
```

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
They look OK to me, e.g. see https://wiki.openstreetmap.org/wiki/Key:source:maxspeed

On an unrelated note, @joeytalbot, @mvl22 and @si-the-pie did a small hackathon on using `osmextract` and have written a reproducible script to combine polygon and point representations of buildings (we did it for buildings in Cambridge). See here if of use/interest: https://github.com/cyipt/actdev/blob/main/code/tests/osmextract.R

We concluded that `osmextract` is a good package that will be very useful for our project!

**Comment by agila5** [comment]
Hi! 

> They look OK to me, e.g. see https://wiki.openstreetmap.org/wiki/Key:source:maxspeed

Thanks for the link! I think there are still some bugs in the function, but unrelated to the previous problem. 

> On an unrelated note, @joeytalbot, @mvl22 and @si-the-pie did a small hackathon on using osmextract and have written a reproducible script to combine polygon and point representations of buildings (we did it for supermarkets in Cambridge). See here if of use/interest: https://github.com/cyipt/actdev/blob/main/code/tests/osmextract.R

Thanks. I'm not sure I understand the problem but if I can help in some way of you find any bug please let me know.

**Comment by agila5** [comment]
> They look OK to me, e.g. see https://wiki.openstreetmap.org/wiki/Key:source:maxspeed

Yes, you're right. I checked the output more carefully and it looks ok. 

> On an unrelated note, @joeytalbot, @mvl22 and @si-the-pie did a small hackathon on using osmextract and have written a reproducible script to combine polygon and point representations of buildings (we did it for supermarkets in Cambridge). See here if of use/interest: https://github.com/cyipt/actdev/blob/main/code/tests/osmextract.R

A just reread that code and I noticed that you included a note saying: _"# todo: get points with SQL"_ If you can add more details, then maybe I can help you.
