### ISSUE TITLE
Question - is there a "datetime" functionality similar to osmdata package?

### ISSUE THREAD

**Issue by cormundo** [ropensci/osmextract#169]

**Comment by agila5** [comment]
Hi and thanks for your question. I'm sorry but, at the moment, there is no built-in `datetime` functionality. I think that it can be added using the historical OSM data stored by Geofabrik but, unfortunately, the website is not reachable now (at least for me). I will add an example as soon as I can load Geofabrik.

**Comment by agila5** [comment]
Hi @cormundo! I just checked on Geofabrik website and I'm quite sure that you can get historical OSM data up to a fixed datetime using the historical `.osh.pbf` files (that can be accessed only with OSM credentials, but that shouldn't be a big problem). The main problem is that you need [`osmium`](https://osmcode.org/) to process the `.osh.pbf` files (or at least a new GDAL driver, I think) and, at the moment, I'm not sure how to implement those changes. Also linked with #141.

**Comment by mpadge** [comment]
@agila5 I would strongly advise against doing this, as it would be [in violation of the OSM license that comes with the data](https://osm-internal.download.geofabrik.de/index.html). You can only provide these data with an accompanying guarantee that people accessing it are also "OpenStreetMap contributors", which you can not do here at all, and for which merely registering an account to get an access key is likely also not sufficient. It really would go against the principle of the OSM license, so I'd close this issue and keep this as a record of why this feature is not and will not be implemented.

**Comment by agila5** [comment]
Hi @mpadge, and thanks for your message. 

> I would strongly advise against doing this, as it would be in violation of the OSM license that comes with the data. You can only provide these data with an accompanying guarantee that people accessing it are also "OpenStreetMap contributors", which you can not do here at all, and for which merely registering an account to get an access key is likely also not sufficient.

I just checked the Geofabrik policy on internal OSM data, and I agree that it would be pretty challenging to ensure that those files are accessible only to OSM contributors. As you said, asking for an OSM account may be sufficient, but I think that writing new code for this purpose may be more trouble than it's worth.

**Comment by mpadge** [comment]
Nice @agila5, but just to clarify, my suggestion was that (merely) asking for an OSM account would likely **NOT** be sufficient, which is the main reason this issue should remain closed :+1:
