### ISSUE TITLE
CRAN error

### ISSUE THREAD

**Issue by agila5** [ropensci/osmextract#175]
Dear maintainer,

Please see
<https://cran.r-project.org/web/checks/check_results_osmextract.html>

The check problems on the Debian systems are caused by attempts to write
to the user library to which all packages get installed before checking
(and which now is remounted read-only for checking).

Having package code which is run as part of the checks and attempts to
write to the user library violates the CRAN Policy's

  Packages should not write in the user’s home filespace (including
  clipboards), nor anywhere else on the file system apart from the R
  session’s temporary directory (or during installation in the location
  pointed to by TMPDIR: and such usage should be cleaned up).

Please correct before 2021-02-26 to safely retain your package on CRAN.

------ 

@Robinlovelace the first CRAN error 😍

**Comment by Robinlovelace** [comment]
Does it write to anything other than tempdir()?

**Comment by agila5** [comment]
Yes, in some cases it was writing to the directory where the package is installed. I'm moving all relevant examples to `tempdir()`.

**Comment by Robinlovelace** [comment]
:+1:
