### ISSUE TITLE
Add support for a local provider

### ISSUE THREAD

**Issue by Sunnymmonkey** [ropensci/osmextract#186]
It would be great if i could host the data myself or keep the files locally.

**Comment by agila5** [comment]
Hi! I'm not sure what you mean, but if you need to keep the downloaded file locally, then you need to set a [persistent download directory](https://github.com/ropensci/osmextract#persistent-download-directory). On the other hand, if you need to save the data imported by `oe_get()` after running the desired (spatial or regular) query, then check `sf::st_write()`. See https://geocompr.robinlovelace.net/read-write.html for more details.

**Comment by Robinlovelace** [comment]
I fully agree with what Andrea says here. Does that solve the issue for you @Sunnymmonkey ? Please close this issue if so and check out the discussion forum if you have any more general questions: https://github.com/ropensci/osmextract/discussions

**Comment by Sunnymmonkey** [comment]
@Robinlovelace  Yes thank you.
