### ISSUE TITLE
`oe_download()` could internally set a `timeout` value

### ISSUE THREAD

**Issue by agila5** [ropensci/osmextract#222]
From the help page of `download.file()`: 

> The timeout for many parts of the transfer can be set by the option timeout which defaults to 60 seconds. This is often insufficient for downloads of large files (50MB or more) and so should be increased when download.file is used in packages to do so. Note that the user can set the default timeout by the environment variable R_DEFAULT_INTERNET_TIMEOUT in recent versions of R, so to ensure that this is not decreased packages should use something like

    options(timeout = max(300, getOption("timeout")))
  
> (It is unrealistic to require download times of less than 1s/MB.)

Most of the .pbf files are larger than 50MB. See also the discussion in #143

**Comment by Robinlovelace** [comment]
Well spotted @agila5 will take a look now :eyes:
