### ISSUE TITLE
[FEATURE] Add function to read .poly files

### ISSUE THREAD

**Issue by agila5** [ropensci/osmextract#277]
See the title

**Comment by Robinlovelace** [comment]
+1 to that. Worth a mini package? Possibly not...

**Comment by agila5** [comment]
I'm not sure, it's literally just 1 function...

**Comment by Robinlovelace** [comment]
1 function pkgs have been known. Will people who don't need all `osmextract` functionality and deps benefit? I guess so, but probably quickest to just add the function here. Can always split it out as a function later.
