### ISSUE TITLE
[BUG] `oe_get_network()` misses links

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/osmextract#289]
**Describe the bug**

As per title.

**To Reproduce**

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(tmap)
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers
leeds = zonebuilder::zb_zone("Leeds", n_circles = 1)
#> Please set segment_center = TRUE to divide the centre into multiple segments
osm = osmextract::oe_get_network("Leeds", boundary = leeds, boundary_type = "clipsrc", mode = "walking")
#> No exact match found for place = Leeds and provider = geofabrik. Best match is Laos. 
#> Checking the other providers.
#> An exact string match was found using provider = bbbike.
#> The chosen file was already detected in the download directory. Skip downloading.
#> Starting with the vectortranslate operations on the input file!
#> 0...10...20...30...40...50...60...70...80...90...100 - done.
#> Warning in CPL_gdalvectortranslate(source, destination, options, oo, doo, :
#> GDAL Message 1: A geometry of type MULTILINESTRING is inserted into layer lines
#> of geometry type LINESTRING, which is not normally allowed by the GeoPackage
#> specification, but the driver will however do it. To create a conformant
#> GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer
#> geometry type. This warning will no longer be emitted for this combination of
#> layer and feature geometry type.
#> Finished the vectortranslate operations on the input file!
#> Reading layer `lines' from data source `/home/robin/data/osm/bbbike_Leeds.gpkg' using driver `GPKG'
#> Simple feature collection with 2898 features and 12 fields
#> Geometry type: MULTILINESTRING
#> Dimension:     XY
#> Bounding box:  xmin: -1.558963 ymin: 53.78843 xmax: -1.528632 ymax: 53.80639
#> Geodetic CRS:  WGS 84
tmap_mode("view")
#> tmap mode set to 'view'
m = qtm(osm)
m
tmap_save(m, "leeds.html")
#> Interactive map saved to /tmp/RtmpiM75xV/reprex-2845a71173f58-girly-unau/leeds.html
browseURL("leeds.html")
```

<sup>Created on 2024-04-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Expected behaviour**

I would expect these links to be present:

![image](https://github.com/ropensci/osmextract/assets/1825120/ee5aad8f-7261-4436-91f1-7b6d31b0f101)

**Additional context**
Add any other context about the problem here. In particular, along with your query, please paste your `devtools::session_info()` or `sessionInfo()` into the code block below. 

https://github.com/nptscot/npt/issues/441

Example of link that's missing (also for driving I think): https://www.openstreetmap.org/way/854772015

Looks like it's because `access == "no"`, which is superceded by `bicycle == "yes"`, although no indication that there's a sidewalk.

**Comment by agila5** [comment]
Thank you very much @Robinlovelace, I totally forgot about it. 

> Looks like it's because access == "no", which is superceded by bicycle == "yes", although no indication that there's a sidewalk.

[OSM wiki](https://wiki.openstreetmap.org/wiki/Key:access?uselang=en-GB) says: _access = no ---> Public access is prohibited on foot and for any vehicle, for every type of person. Stronger interdiction than [private](https://wiki.openstreetmap.org/wiki/Tag:access%3Dprivate). It is necessary to add additional access (like [foot](https://wiki.openstreetmap.org/wiki/Key:foot)=[yes](https://wiki.openstreetmap.org/wiki/Tag:foot%3Dyes) or [bicycle](https://wiki.openstreetmap.org/wiki/Key:bicycle)=[permissive](https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Dpermissive), etc.) to indicate who may use the element, if anyone is allowed._

Working on it right now!
