### ISSUE TITLE
Revdep error (sf 1.0.16, GDAL 3.9.0 beta1, R 4.4.0)

### ISSUE THREAD

**Issue by rsbivand** [ropensci/osmextract#291]
There is an error detected when running revdeps on `sf` and `terra` for the forthcoming GDAL 3.9.0 for R CMD check on this package: 
[00check.log](https://github.com/ropensci/osmextract/files/15106826/00check.log).

Stepping through the vignette code, I see:
```
Warning message:
In CPL_gdalvectortranslate(source, destination, options, oo, doo,  :
  GDAL Error 1: Field ' highway' not found in source layer.
```
then:
```
Error in sf::gdal_utils(util = "vectortranslate", source = normalizePath(file_path),  : 
  gdal_utils vectortranslate: an error occured
```

Is this the GDAL version, has something changed internally, or is `highway` actually absent?

**Comment by Robinlovelace** [comment]
Thanks for the report Roger. Not sure what's going on... Thoughts Andrea?

**Comment by rsbivand** [comment]
The error is at: https://github.com/ropensci/osmextract/blob/20742aa0296c6a5c1c9e15bf587fc9a6e657b82e/vignettes/osmextract.Rmd#L611, eventually from: https://github.com/ropensci/osmextract/blob/20742aa0296c6a5c1c9e15bf587fc9a6e657b82e/R/vectortranslate.R#L455 after a fair number of steps.

**Comment by edzer** [comment]
Removing the space before `highway` here: https://github.com/ropensci/osmextract/blob/20742aa0296c6a5c1c9e15bf587fc9a6e657b82e/vignettes/osmextract.Rmd#L602
resolves the vignette error.

**Comment by agila5** [comment]
Thank you very much @rsbivand and @edzer for raising this issue and diagnosing/correcting the error in the vignette. Should be fixed now. Will submit to CRAN during the next week.

**Comment by rsbivand** [comment]
Yes, when the space is removed, this now is fixed: 
[00check.log](https://github.com/ropensci/osmextract/files/15118959/00check.log)

**Comment by Robinlovelace** [comment]
Impressively fast problem identification, diagnosis, and fix! Many thanks.

**Comment by agila5** [comment]
Thanks again! Nice example that the new approach in GDAL 3.9.0 works 😅
