### ISSUE TITLE
[FEATURE] Add the `oneway` tag to the driving network

### ISSUE THREAD

**Issue by juanfonsecaLS1** [ropensci/osmextract#296]
**Is your feature request related to a problem? Please describe.**
The `oneway` tag indicates if any of the lines representing a road is unidirectional. Having that column by default is useful, for example,
when building the graph representation of the network with `dodgr` for motorised modes.

**Describe the solution you'd like**
Adding the tag `oneway` to the `extra_tags` parameter of `load_options_driving` would be enough.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by agila5** [comment]
Fixed by #297
